Event for successful DD launches
tgstation/tgstation-server pull request #1251
Opened 2021-04-28 13:32 UTC by AffectedArc07

This PR adds in an event that is called when DD successfully launches. Similar to `WatchdogLaunch`, except it occurs any time a DD process is launched during the same watchdog session. The PID is given as a script argument, which can be used for many things, including but not limited to:
- Auto-nicing the correct DD process to a custom value on linux
- Modifying performance trackers to use the right PID
- Modifying other system monitors that look for the DD PID
- Etc

Includes a DMAPI version bump since that was asked for with the last event 

:cl: Core
Added an event for successful production DD launches. Has the DD PID as an argument
/:cl:

2021-04-28 14:28 UTC, AffectedArc07 commented
`Error: API rate limit exceeded for installation ID 5334476.`

I hate CI sometimes

2021-04-28 16:07 UTC, Cyberboss requested changes

2021-04-28 16:07 UTC, Cyberboss commented on src/Tgstation.Server.Host/Components/Session/SessionControllerFactory.cs
> +			bool isProduction,
Just use apiValidate, the extra parameter isn't needed

2021-04-28 16:07 UTC, Cyberboss commented on src/Tgstation.Server.Host/Components/Session/SessionControllerFactory.cs
> +						await EventConsumer.HandleEvent(EventType.WatchdogSuccessfulLaunch, new List<string>
Braces unncessary for this if

2021-04-28 16:07 UTC, Cyberboss commented on src/Tgstation.Server.Host/Components/Session/SessionControllerFactory.cs
> +		private IEventConsumer EventConsumer { get; }
Make it a readonly field, put it with the other interfaces, above the logger factory

2021-04-28 16:07 UTC, Cyberboss commented on src/Tgstation.Server.Host/Components/Session/SessionControllerFactory.cs
> +			EventConsumer eventConsumer)
Move the param above the logger factory

2021-04-28 16:07 UTC, Cyberboss commented on src/Tgstation.Server.Host/Components/Session/SessionControllerFactory.cs
> +			EventConsumer = eventConsumer ?? throw new ArgumentNullException(nameof(eventConsumer));
assignment above the logger factory

2021-04-28 16:07 UTC, Cyberboss commented on src/Tgstation.Server.Host/Components/Events/EventType.cs
> +		WatchdogSuccessfulLaunch,
Call it DreamDaemonLaunch, at the time you call the event, you never checked to see if the launch was successful

2021-04-28 16:08 UTC, Cyberboss commented
Also, you know TGS already tries to nice the process right?

2021-04-28 16:09 UTC, Cyberboss requested changes

2021-04-28 16:09 UTC, Cyberboss commented on src/Tgstation.Server.Host/Components/Session/SessionControllerFactory.cs
> +						}, cancellationToken).ConfigureAwait(false);
```suggestion
						await EventConsumer.HandleEvent(
							EventType.WatchdogSuccessfulLaunch,
							new List<string>
							{
								process.Id.ToString(CultureInfo.InvariantCulture)
							},
							cancellationToken)
							.ConfigureAwait(false);
```

2021-04-28 16:09 UTC, AffectedArc07 commented
> Also, you know TGS already tries to nice the process right?

Yes, however when I tested this, DD niced at **-6**. That and the other use cases follow.

2021-04-28 17:48 UTC, AffectedArc07 commented on src/DMAPI/tgs.dm
> +// #define TGS_EVENT_WATCHEDOG_LAUNCH_SUCCESS 22
```suggestion
// #define TGS_EVENT_DREAM_DAEMON_LAUNCH 22
```

2021-04-28 19:40 UTC, Cyberboss requested changes

2021-04-28 19:40 UTC, Cyberboss commented on src/Tgstation.Server.Host/Components/Session/SessionControllerFactory.cs
> +					if(!apiValidate)
Move this down to after where the SessionController is created

2021-04-29 15:25 UTC, Cyberboss approved these changes

2021-04-29 15:25 UTC, merged