Security check
tgstation/tgstation-server pull request #1348
Opened 2021-11-05 02:51 UTC by TheFakeElon

[Base Branch]: master

[Release Notes]: fixes a security flaw in tgs3

:cl:
fixes a security flaw
/:cl:

2021-11-05 15:54 UTC, ExcessiveUseOfCobblestone approved these changes

2021-11-15 10:43 UTC, LemonInTheDark commented
Mothblocks is blind #1349

2021-11-15 10:44 UTC, LemonInTheDark commented
wait wrong version

2021-11-18 10:15 UTC, MCterra10 commented
can we merge this already?

2021-11-18 10:42 UTC, LemonInTheDark commented
no, because it breaks servers that don't have that proc (Insert better reason cyber will give here)
This whole thing is so mindnummingly dumb I wish to return to an era before security posting

2021-12-02 03:32 UTC, alexkar598 requested changes

2021-12-02 03:32 UTC, alexkar598 commented on src/DMAPI/tgs/v3210/api.dm
> +		CRASH("Attempted to read file via admin call")
This proc is not part of DMAPI

2021-12-12 16:51 UTC, AffectedArc07 commented
The real fix here is to stop using deprecated software which was coded in one afternoon while cyberboss was stoned
![image](https://user-images.githubusercontent.com/25063394/145721523-7ccd3f3e-5022-44d4-8de2-30382afaf1c7.png)

2021-12-12 16:57 UTC, AffectedArc07 commented
Putting another post. You can mitigate this on your own codebases outside of the DMAPI. Here are a few ways in no particular order:
- `GENERAL_PROTECT_DATUM(/datum/tgs_api/v3210)`
- Defining a proc after this to make inheritence work. Just put this in your codebase after your DMAPI folder
```
/datum/tgs_api/v3210/file2list(filename)
	if(IsAdminAdvancedProcCall())
		CRASH("Attempted to read file via admin call")
	..()
```

2021-12-12 23:59 UTC, Cyberboss commented
Various reasons/alternative already stated, plus you could always redefine file2text. Modifying external library code is not the wei here.

2021-12-12 23:59 UTC, closed without merging

2023-06-04 19:55 UTC, Cyberboss commented
Revisionist history 
![image](https://github.com/tgstation/tgstation-server/assets/8171642/83ea0ed6-602c-481b-8b14-ddd0f5c0ed1e)